language: ruby
cache: bundler
rvm:
- 2.5.1
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake db:seed
script:
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: OI4gjLr1UDjKtnJoums5nGnPnX4kNCE1IUyUd/TWeyPdcs9tP7vzNno6wJKjd7HOTCAvt+wAPlCIbPa4GxS25nRDSlVpGSmmPahKSAlQyDez2B76M/d5Nx97KC5+SOoV9b208BmjR8ng2WFZgPyCckU6Ub1JUC3bvw5Bu+VNrNFJORlkAw/EvBN7hMS3GYS/WD38/gG9SZugQb/Q41tAEj7N0djbDUWRNrzbIVcYUscdSjkxD3+lFdthIoF3qXkuJg74772EDbS9jJEzR+LWYluWeFsokVjo0oxZh8wLOB0+QWOS6Qmpu8Iktmk8a95hl9/t5plmnLTyc9pJYmSICsl6mrpxlq0Nw2TT2eaoGr0DMDpTUygWQQUWcHPa6BM8HdsU3EiQAB3vpLh5lbbYtYCu9L9V1Ggm0MAbgj0mc0YrCXq/ULpqWC18VPWr42cf88U4KCGItXeLIfA5slC8DpZlw6XxXMoL7WWura8ESiPEdjP2bzc+donYqM8h6fOYbRCUthq8BqejBjLWPtzi+x+i/CbYtSJK4M+HNEqsNCG/mpCxNgsfrRW7aiR9F33V+uUgiwwp16FvG0aGVL3oNCLBTJOaKsTzroHm5GSAAP5sR2D9Ax3+IUzL4k3cau/ONSvEbXi10W+exy6ISd21azBFXPcPH2pkTOGDnxgkhns=
  app: maicers-acebook-api
  run:
  - rake db:migrate
