language: ruby
cache: bundler
rvm:
- 2.5.1
before_script:
- bundle exec rake db:reset
- bundle exec rake db:seed
script:
- bundle exec rspec spec
deploy:
  provider: heroku
  app: maicers-acebook-api
  api_key:
    secure: NjJojItHdwga9WBre8uJHRb2lY7D6JSnwb9T3LU7DVdGyLuD6g+wHmQALutsgLcutsBdqO3AxQMPb6xzy6UT3gIs64ADaYY5fo+wCRGoW3WbXYIWSnMXDZS9R2ic6pwh7UekK29BzdgzaCODHDhsTHnQY0yiwIrNu5KwS+H6vgvQFKzl+X62m69QHTiRtav0hFUoXSvhdGkaiCREONDypPBCzn2u3cDDa0fsT6xQkE4CPPt2Cy9D0uB4RJ17J0ZeT4POpDnCGOBE7+xmQxT1MCidCPk5zUhBwxkgrm5rHBWnQa9xZMt+Tz6tu6P0lGgh1fi/uyBeNqkhH3mYrv1iOLX0xBdBpap7cr1vKyV8pAaKrMAEB90ZozoZcalK7p0jZSqYmmxl+G25hx6KIusk8SPeCSAKamk6OvMM8fFwX5sJMSIoMUrvM/J0zdnL9rK1paiD3hLfXH2cq48Tyf5HiZmhIr6wl9eewPNIm9NaRWi+YbDhXFaZPel4UWLnUkZDbuOJMt+pvJHFohfufpnCQY7/62Ud13UxVoib6xG0MsODzRVTHmmbXOc+0MJ/bORjAUIOCmXhiXFVU9K7HovvLSS/lVh21ycmUWeA6wioQTlYlkFF8JchyTvSWcE4enxWJLYBUyVcNhw+C/Xz1KghzDxKcYuQJpptww+rqIZWj2Y=
